name: Build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            linux-tools-generic \
            libbpf-dev \
            libnl-3-dev \
            libnl-route-3-dev \
            libelf-dev \
            libcgroup-dev
      - name: Build
        run: make dev