name: Valgrind
on: [pull_request]
jobs:
  valgrind:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            linux-tools-generic \
            linux-tools-azure \
            linux-cloud-tools-azure \
            libbpf-dev \
            libnl-3-dev \
            libnl-route-3-dev \
            libcmocka-dev \
            libelf-dev \
            libcgroup-dev \
            gcc-multilib \
            libc6-dev \
            valgrind
      - name: Run Valgrind
        run: make valgrind
